# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ulises Reyes
email: hi@ulises.me
description: > # this means to ignore newlines until "baseurl:"
  Ulises Reyes | Designer
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://ulises.me" # the base hostname & protocol for your site
twitter_username: ureys
github_username:  urjr

color:
  home_color: "3498db"
  about_color: "2ecc71"
  work_color: "e67e22"
  blog_color: "9b59b6"
  sandbox_color: "7f8c8d"

# Build settings
markdown: kramdown

# Server Config options
livereload: true     # You no longer need to include --livereload

gems: [bourbon, neat]
